language: node_js
os: linux
  - "6"
dist: trusty
sudo: required
install:
  - npm install
addons:
  chrome: stable
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
cache:
  directories:
    - "node_modules"
before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
    - npm run lint
script:
  - npm run test:chrome
  - npm run coverage
after_success:
  - npm run coveralls
